/* ================= کمپین «خط آهن آخر» ================= */
const campaignMission=(id,act,title,briefing,primary,optional,enemies,airProfile,sceneId,weather,palette,runtime,persistentEffect,reward)=>Object.freeze({
  id,act,mapNode:id,title,briefing,
  primaryObjective:Object.freeze(primary),optionalObjective:Object.freeze(optional),enemyRoster:Object.freeze(enemies),
  airProfile,sceneId,weather,palette,runtime:Object.freeze(runtime),persistentEffect,reward:Object.freeze(reward)
});
const CAMPAIGN_MISSIONS=Object.freeze([
  campaignMission('M01',1,'آتش در سرو','در سپیده‌دم بارانی، کاروان مرزی زیر آتش است؛ راه خروج را باز کن.',{kind:'operation',value:3,label:'کاروان را از آتش، جاده و دیده‌بان عبور بده'},{kind:'protect',value:3,label:'هر سه کامیون را سالم نگه دار'},['light','light','medium'],'none','scene-01','rain','dawn',{t:'operation',v:3,c:1,operation:'opening-convoy'},null,{stars:3,label:'نشان نگهبان سرو'}),
  campaignMission('M02',1,'خاک نرم','ستون باید از مسیر فرعی باتلاقی خارج شود.',{kind:'survive',value:75,label:'کاروان را تا خروجی هدایت کن'},{kind:'protect',value:3,label:'کامیون‌ها در گل نمانند'},['light','medium'],'none','scene-02','mist','day',{t:'survive',v:75,c:1},null,{stars:3,label:'مسیر ایمن'}),
  campaignMission('M03',1,'پل یک‌نفره','دیده‌بان دشمن تنها گذرگاه ستون را هدف گرفته است.',{kind:'destroy',value:5,label:'دو سوی پل را پاکسازی کن'},{kind:'protect',value:1,label:'پل را سالم نگه دار'},['light','medium'],'none','scene-03','rain','day',{t:'destroy',v:5,c:1},null,{stars:3,label:'اعتماد مقاومت'}),
  campaignMission('M04',1,'چراغ‌های خاموش','چراغ‌گردان‌های دشمن کمین‌های شبانه را هدایت می‌کنند.',{kind:'assault',value:3,label:'سه چراغ‌گردان را خاموش کن'},{kind:'protect',value:4,label:'خانه‌ها را حفظ کن'},['light','light','medium'],'none','scene-04','rain','night',{t:'assault',v:3,c:1},null,{stars:3,label:'گل مرداب'}),
  campaignMission('M05',1,'مه بالای رهان','دیده‌بان‌های هوایی دشمن جای کاروان را در مه جست‌وجو می‌کنند.',{kind:'destroy',value:4,label:'به پناهگاه نیزاری برس'},{kind:'destroy',value:2,label:'بالن‌ها را نابود کن'},['light','medium'],'scout','scene-05','mist','day',{t:'destroy',v:4,c:1},null,{stars:3,label:'هشدار هوایی'}),
  campaignMission('M06',1,'دندان سنگی','توپ ضدتانک جاده را بسته و مسیر پهلویی تنها راه است.',{kind:'boss',value:1,label:'توپ ضدتانک را از پهلو منهدم کن'},{kind:'survive',value:40,label:'از شلیک نخست جان سالم ببر'},['medium','heavy'],'none','scene-06','rain','dusk',{t:'boss',v:1,c:1,bossHp:550,bossName:'دندان سنگی'},null,{stars:3,label:'شلیک از پهلو'}),
  campaignMission('M07',1,'باند متروک','دشمن باند محلی را برای سوخت‌گیری هواپیماهای ضربتی فعال می‌کند.',{kind:'assault',value:3,label:'سه کامیون سوخت را نابود کن'},{kind:'protect',value:1,label:'برج کنترل را حفظ کن'},['medium','light'],'strike','scene-07','dusk','dusk',{t:'assault',v:3,c:1},null,{stars:3,label:'مسیر تأسیسات هوایی'}),
  campaignMission('M08',1,'انبار سرخ','انبار سوخت زرهی دشمن در لبه دشت پیدا شده است.',{kind:'assault',value:5,label:'مخزن‌ها و رادیوی کمپ را نابود کن'},{kind:'protect',value:1,label:'جرثقیل بارگیری را حفظ کن'},['medium','heavy'],'strike','scene-08','dusk','dusk',{t:'assault',v:5,c:1},'fuelCut',{stars:3,label:'قطع سوخت دشمن'}),
  campaignMission('M09',1,'قطار بی‌صدا','دشمن برای جبران سوخت، قطار زرهی می‌فرستد.',{kind:'destroy',value:7,label:'قطار را پیش از سوزن متوقف کن'},{kind:'protect',value:1,label:'واگن دارو را حفظ کن'},['medium','light','heavy'],'strike','scene-09','rain','night',{t:'destroy',v:7,c:1},null,{stars:3,label:'نشان راه‌آهن'}),
  campaignMission('M10',1,'خروج از باران','مرز سقوط کرده اما ستون واردان ضدحمله را انتخاب می‌کند.',{kind:'boss',value:1,label:'کاروان را تا ارما برسان'},{kind:'destroy',value:1,label:'تانک فرمانده را نابود کن'},['medium','heavy'],'strike','scene-10','rain','dawn',{t:'boss',v:1,c:1,bossHp:750,bossName:'فرمانده مرزی'},null,{stars:3,label:'ضدحمله آغاز شد'}),
  campaignMission('M11',2,'پل شیشه‌ای','تنها ورودی شهر از دو سوی رود زیر آتش است.',{kind:'destroy',value:6,label:'پل را بازپس بگیر'},{kind:'protect',value:1,label:'دهانه میانی پل را حفظ کن'},['medium','heavy'],'strike','scene-11','mist','day',{t:'destroy',v:6,c:2},null,{stars:3,label:'پل‌ساز'}),
  campaignMission('M12',2,'بازار سوخته','انبار مهمات میان خیابان‌های تله‌گذاری‌شده پنهان است.',{kind:'assault',value:5,label:'سه انبار را منهدم کن'},{kind:'protect',value:1,label:'مسیر امداد را باز نگه دار'},['light','medium'],'none','scene-12','smoke','dusk',{t:'assault',v:5,c:2},null,{stars:3,label:'میانبر کارخانه'}),
  campaignMission('M13',2,'کارخانه بی‌خواب','دشمن در سالن‌های صنعتی تانک‌های آسیب‌دیده را تعمیر می‌کند.',{kind:'destroy',value:8,label:'سکوهای تعمیر را از کار بینداز'},{kind:'protect',value:1,label:'ژنراتور مقاومت را حفظ کن'},['medium','heavy'],'none','scene-13','smoke','dusk',{t:'destroy',v:8,c:2},null,{stars:3,label:'نقشه کمپ'}),
  campaignMission('M14',2,'چشم آسمان','رادار دشمن زمان یورش‌های هوایی را تعیین می‌کند.',{kind:'assault',value:5,label:'آنتن و ژنراتور را نابود کن'},{kind:'protect',value:1,label:'برج مقاومت را حفظ کن'},['medium','heavy'],'strike','scene-14','wind','day',{t:'assault',v:5,c:2},'airIntel',{stars:3,label:'اطلاعات هوایی'}),
  campaignMission('M15',2,'کانال سرد','بارج‌های مهمات به شمال می‌روند و دیواره کانال تنها پوشش است.',{kind:'destroy',value:7,label:'بارج‌ها را متوقف کن'},{kind:'protect',value:1,label:'دریچه آب را حفظ کن'},['medium','light'],'strike','scene-15','mist','dawn',{t:'destroy',v:7,c:2},null,{stars:3,label:'مسیر بندر'}),
  campaignMission('M16',2,'سایه برج‌ها','فرماندهی دشمن چهارراه‌های شهر را از برج ساعت کنترل می‌کند.',{kind:'boss',value:1,label:'پست فرماندهی را تسخیر کن'},{kind:'destroy',value:3,label:'دیده‌بان‌ها را پیش از کمک نابود کن'},['medium','heavy'],'none','scene-16','rain','dusk',{t:'boss',v:1,c:2,bossHp:950,bossName:'برج ساعت'},null,{stars:3,label:'رمز پدافند'}),
  campaignMission('M17',2,'باند دوم','رمزها، دسترسی به باند اصلی ضربتی دشمن را ممکن می‌کند.',{kind:'assault',value:5,label:'برج و انبارها را نابود کن'},{kind:'protect',value:1,label:'هواپیمای خودی را پوشش بده'},['medium','heavy'],'strike','scene-17','dusk','dusk',{t:'assault',v:5,c:2},null,{stars:3,label:'پشتیبانی آزمایشی'}),
  campaignMission('M18',2,'آتش پدافند','پیش از ورود هواگرد خودی، حلقه پدافند باید خاموش شود.',{kind:'assault',value:6,label:'توپ‌ها و فرماندهی را نابود کن'},{kind:'protect',value:1,label:'سوخت اضطراری را حفظ کن'},['heavy','medium'],'strike','scene-18','dawn','dawn',{t:'assault',v:6,c:2},'flakBroken',{stars:3,label:'شکست پدافند'}),
  campaignMission('M19',2,'سپر نوین','ستون زرهی برای بازپس‌گیری شهر نزدیک می‌شود.',{kind:'waves',value:5,label:'میدان را حفظ کن'},{kind:'support',value:1,label:'ستون را نشانه‌گذاری کن'},['medium','heavy','light'],'support','scene-19','smoke','dusk',{t:'waves',v:5,c:2},null,{stars:3,label:'سپر شهر'}),
  campaignMission('M20',2,'ایستگاه صفر','تیم تخریب می‌خواهد کنترل ریل شمال را منفجر کند.',{kind:'boss',value:1,label:'تخریب را متوقف کن'},{kind:'protect',value:1,label:'قطار مجروحان را پوشش بده'},['heavy','medium'],'support','scene-20','steam','dawn',{t:'boss',v:1,c:2,bossHp:1150,bossName:'تیم تخریب'},'railOpen',{stars:3,label:'راه شمال'}),
  campaignMission('M21',3,'ریل برفی','قطار اطلاعات در بهمن کوچک متوقف شده است.',{kind:'destroy',value:9,label:'ریل را پاکسازی کن'},{kind:'protect',value:1,label:'واگن شنود را حفظ کن'},['light','medium'],'strike','scene-21','snow','dawn',{t:'destroy',v:9,c:3},null,{stars:3,label:'مسیر ایمن'}),
  campaignMission('M22',3,'صدای درختان','گروه مقاومت در دل جنگل محاصره شده است.',{kind:'survive',value:90,label:'گروه را نجات بده'},{kind:'protect',value:1,label:'کاروان آسیب نبیند'},['light','medium'],'none','scene-22','mist','day',{t:'survive',v:90,c:3},null,{stars:3,label:'دیده‌بانی مقاومت'}),
  campaignMission('M23',3,'معدن خاموش','مهمات دشمن زیر تونل‌ها پنهان شده است.',{kind:'assault',value:6,label:'دو انبار را نابود کن'},{kind:'protect',value:1,label:'جرثقیل معدن را حفظ کن'},['medium','heavy'],'none','scene-23','mist','dusk',{t:'assault',v:6,c:3},null,{stars:3,label:'مهمات مقاومت'}),
  campaignMission('M24',3,'گردنه کور','ستون دشمن در مه به سوی سد می‌رود.',{kind:'destroy',value:10,label:'خودروهای پیشرو را متوقف کن'},{kind:'protect',value:1,label:'خودرو امدادی عبور کند'},['medium','heavy'],'strike','scene-24','snow','day',{t:'destroy',v:10,c:3},null,{stars:3,label:'راه‌بند'}),
  campaignMission('M25',3,'آب سیاه','شیرهای فرعی روستای پایین‌دست را تهدید می‌کنند.',{kind:'assault',value:6,label:'سه شیر را امن کن'},{kind:'destroy',value:1,label:'برج دیده‌بانی را آزاد کن'},['medium','light'],'strike','scene-25','rain','dusk',{t:'assault',v:6,c:3},null,{stars:3,label:'نقشه کانال'}),
  campaignMission('M26',3,'ایستگاه شنود','کدهای فرمان حمله هوایی از این دکل عبور می‌کند.',{kind:'destroy',value:9,label:'فرستنده‌ها را اسکن کن'},{kind:'protect',value:1,label:'دکل اصلی سالم بماند'},['medium','heavy'],'strike','scene-26','snow','night',{t:'destroy',v:9,c:3},null,{stars:3,label:'کدهای رادار'}),
  campaignMission('M27',3,'شبکه کور','کدها جای رادار اصلی را در طوفان آشکار کرده‌اند.',{kind:'assault',value:7,label:'رادار و کابل را نابود کن'},{kind:'protect',value:1,label:'دیده‌بان را خارج کن'},['heavy','medium'],'strike','scene-27','snow','night',{t:'assault',v:7,c:3},'radarBlind',{stars:3,label:'رادار کور'}),
  campaignMission('M28',3,'پل یخ‌زده','نقشه سد باید از پلی با کابل‌های آسیب‌دیده عبور کند.',{kind:'survive',value:105,label:'پل را تا عبور کاروان حفظ کن'},{kind:'destroy',value:2,label:'مین‌گذارها را نابود کن'},['medium','heavy'],'strike','scene-28','snow','dawn',{t:'survive',v:105,c:3},null,{stars:3,label:'کابل آخر'}),
  campaignMission('M29',3,'دژ بیرونی','نقشه پدافند روی دیوارهای دژ آزمایش می‌شود.',{kind:'boss',value:1,label:'سنگرها را بشکن'},{kind:'protect',value:1,label:'انبار پزشکی را حفظ کن'},['heavy','medium'],'strike','scene-29','snow','night',{t:'boss',v:1,c:3,bossHp:1400,bossName:'دژ بیرونی'},null,{stars:3,label:'طرح انبار'}),
  campaignMission('M30',3,'ذخیره خاکستر','پیش از یورش، سوخت و مهمات دشمن باید بسوزد.',{kind:'assault',value:8,label:'محموله‌ها و تعمیرکارها را نابود کن'},{kind:'protect',value:1,label:'در خروج مقاومت را حفظ کن'},['heavy','medium'],'strike','scene-30','snow','night',{t:'assault',v:8,c:3},'supplyBurned',{stars:3,label:'ذخیره نابود شد'}),
  campaignMission('M31',4,'راه آب','کاروان مهندسی نخستین گام ضدحمله است.',{kind:'survive',value:110,label:'کاروان را به پمپاژ برسان'},{kind:'protect',value:3,label:'هر سه وسیله سالم بمانند'},['medium','heavy'],'strike','scene-31','rain','dawn',{t:'survive',v:110,c:4},null,{stars:3,label:'راه آب'}),
  campaignMission('M32',4,'دریچه سوم','سه دریچه قفل شده و آب پایین‌دست را تهدید می‌کند.',{kind:'assault',value:7,label:'سه دریچه را آزاد کن'},{kind:'protect',value:2,label:'دو مهندس را برسان'},['medium','heavy'],'none','scene-32','steam','dusk',{t:'assault',v:7,c:4},null,{stars:3,label:'کنترل آب'}),
  campaignMission('M33',4,'ستون فولاد','آخرین ستون زرهی می‌خواهد محاصره را بشکند.',{kind:'destroy',value:12,label:'ستون را در سه نقطه متوقف کن'},{kind:'boss',value:1,label:'فرمانده را پیش از تونل نابود کن'},['heavy','medium','light'],'strike','scene-33','smoke','dusk',{t:'destroy',v:12,c:4},null,{stars:3,label:'ستون شکست'}),
  campaignMission('M34',4,'تونل شماره هفت','تنها مسیر پشت دیوارها با مین و درهای سنگین بسته شده است.',{kind:'assault',value:7,label:'کنترل‌های در را فعال کن'},{kind:'protect',value:1,label:'برق تونل را حفظ کن'},['light','medium'],'none','scene-34','steam','night',{t:'assault',v:7,c:4},null,{stars:3,label:'مسیر مخفی'}),
  campaignMission('M35',4,'نشان سد','فرستنده دشمن زمان انفجار دریچه‌ها را حمل می‌کند.',{kind:'destroy',value:10,label:'اتاق فرستنده را امن کن'},{kind:'protect',value:1,label:'آنتن سالم بماند'},['medium','heavy'],'strike','scene-35','wind','night',{t:'destroy',v:10,c:4},'damSignal',{stars:3,label:'سیگنال سد'}),
  campaignMission('M36',4,'آسمان باز','آخرین توپ‌ها باید خاموش شوند تا پنجره هوایی باز شود.',{kind:'assault',value:7,label:'توپ‌ها و برج را نابود کن'},{kind:'protect',value:1,label:'هواپیمای شناسایی برخیزد'},['heavy','medium'],'strike','scene-36','wind','dusk',{t:'assault',v:7,c:4},null,{stars:3,label:'پنجره هوایی'}),
  campaignMission('M37',4,'دیوار آخر','سرو-۳۴ باید شکاف امنی برای توپ خودی بسازد.',{kind:'boss',value:1,label:'برجک‌ها و دروازه را بشکن'},{kind:'protect',value:1,label:'توپ خودی به موضع برسد'},['heavy','medium'],'strike','scene-37','snow','night',{t:'boss',v:1,c:4,bossHp:1650,bossName:'دیوار آخر'},null,{stars:3,label:'شکاف دژ'}),
  campaignMission('M38',4,'پنجره آبی','آخرین شبکه ضدهوایی باید خاموش شود.',{kind:'assault',value:8,label:'رادار و پدافند را نابود کن'},{kind:'destroy',value:1,label:'برج مقاومت را آزاد کن'},['heavy','medium'],'none','scene-38','snow','night',{t:'assault',v:8,c:4},'skyWindow',{stars:3,label:'پشتیبانی نهایی'}),
  campaignMission('M39',4,'فرمان وارن','شمارش معکوس انفجار دریچه‌ها آغاز شده است.',{kind:'boss',value:1,label:'سه رله را نابود و به مرکز برس'},{kind:'support',value:1,label:'پشتیبانی را هوشمند مصرف کن'},['heavy','medium'],'support','scene-39','storm','night',{t:'boss',v:1,c:4,bossHp:1850,bossName:'فرمان وارن'},null,{stars:3,label:'توقف شمارش'}),
  campaignMission('M40',4,'خط آهن آخر','وارن می‌گریزد و باید آب و خط آهن دوباره امن شوند.',{kind:'boss',value:1,label:'تانک وارن و دریچه اصلی را متوقف کن'},{kind:'protect',value:1,label:'قطار تعمیر از پل بگذرد'},['heavy','medium'],'none','scene-40','dawn','dawn',{t:'boss',v:1,c:4,bossHp:2200,bossName:'وارن، فرمانده خاکستر'},null,{stars:3,label:'خط آهن آخر'})
]);
CAMPS=['مرز خاکستر','رود آهن','کوهستان خاموش','راه آخر'];
MISSIONS=CAMPAIGN_MISSIONS.map(m=>({n:m.title,d:m.briefing,t:m.runtime.t,v:m.runtime.v,p:m.palette,c:m.act,bossName:m.runtime.bossName,bossHp:m.runtime.bossHp}));
function getCampaignMission(id){return CAMPAIGN_MISSIONS.find(m=>m.id===id)||null;}
